### ISSUE TITLE
vibrant brutalist view transition

### ISSUE THREAD

**Issue by KaanKalmi** [KaanKalmi/user-needs#3]
![image](https://github.com/user-attachments/assets/2089c50c-4e08-4594-b920-4032d94ea108)

> Heb de concept verandert, deze klonk leuker

**Comment by KaanKalmi** [comment]
```css
@view-transition {
   navigation: auto;
}
```

Cross-document, normale `<a>` view transition, CSS Only (Cross-fade animation)

**Comment by KaanKalmi** [comment]
Je hebt geen `<meta>` meer nodig, zolang de stylesheet op hetzelfde domein staat

**Comment by KaanKalmi** [comment]
Same document view transition (JS)
`document.startViewTransition`

**Comment by KaanKalmi** [comment]
Same document view transition demo
```js
class.addEventListener('clicl', function() {
   if (document.startViewTransition) {
      document.startViewTransition(toggleActiveState)
      } else {
         toggleActiveState 
         }
     })
```   

```css
::view-transition(animatie) {
   animation-duration: 3s; (je kan hier properties van je view transition animatie veranderen)
}
```

Je zet eht erin met JS, verandert met CSS dus!
